Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [8]:
import numpy as np
np.array([1, 2, 3,0])

array([1, 2, 3, 0])

In [ ]:
Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [9]:
np.diag(np.arange(1,3), k=-1)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 2, 0]])

Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [63]:
import numpy
a = np.array( [ [4, 2,1], [1, 3, 0] ,[5,0, 4]] )
b = np.array( [4, 12, -3] )
linalg.solve(a, b)

array([-1.56,  4.52,  1.2 ])

Задача 4 
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [93]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
ext_user_stats = np.array([0, 1, 2, 0, 0, 0])
def cosine(users_stats, ext_user_stats):
    aLength = np.linalg.norm(users_stats) 
    bLength = np.linalg.norm(ext_user_stats)
    return np.dot(users_stats, ext_user_stats) / (aLength * bLength)